name: NodeJS with Webpack

on:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Tests
      run: |
        npm install
        npm run test

  merge-to-main:
    permissions:
      contents: write # возможно не нужно
    needs: tests # Запускать только если тест прошёл успешно
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - run: echo "✅ Starting process to merge Develop into Main on the ${{ github.repository }}."
        
      - name: Merge develop into main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge develop -m "Github Actions - Auto-merge Develop to Main"
          git push
      - run: echo "📣 This job's status is ${{ job.status }}."
