name: NodeJS with Webpack

on:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Tests
      run: |
        npm install
        npm run test

  merge-to-main:
    needs: tests # Запускать только если тест прошёл успешно
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
      - uses: actions/checkout@main
      - name: Merge develop -> main
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }}
