name: NodeJS with Webpack

on:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Tests
      run: |
        npm install
        npm run test

  merge-to-main:
    needs: tests # Запускать только если тест прошёл успешно
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Необходимо для полной истории коммитов

      - name: Merge develop into main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: pr
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
