name: NodeJS with Webpack

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Tests
      run: |
        npm install
        npm run test
    
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: install node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '16.14.0'

  #   - name: Build
  #     run: |
  #       npm install
  #       npm run build
