name: NodeJS with Webpack

on:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Tests
      run: |
        npm install
        npm run test

  merge-to-main:
    permissions:
      contents: write
    needs: tests # Запускать только если тест прошёл успешно
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0 # Важно для merge

    - name: Configure Git
      run: |
        git config --global user.email "nail361@mail.ru"
        git config --global user.name "nail361"

    - name: Merge develop to master
      run: |
        git fetch origin main
        git checkout main
        git merge --no-ff develop
        git push origin main
